"""Contract tests for the app-facing generated feature reference (#43)."""

import sys
from pathlib import Path

import pytest
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tlhdig import TF_VERSION


def fd():
    """Import inside tests so RED is test failure, not collection failure."""
    from tlhdig import featuredocs

    return featuredocs


def write_tf(path: Path, header: str, body: str = "1\tx\n") -> Path:
    path.write_text(header.rstrip("\n") + "\n\n" + body, encoding="utf8")
    return path


def test_read_header_classifies_node(tmp_path):
    path = write_tf(
        tmp_path / "lemma.tf",
        "@node\n@description=lexical lemma\n@valueType=str\n@version=9.9.9",
    )
    h = fd().read_header(path)
    assert h.kind == "node"
    assert h.valued is False
    assert h.metadata["description"] == "lexical lemma"
    assert h.metadata["version"] == "9.9.9"


def test_value_type_does_not_make_an_edge_valued(tmp_path):
    path = write_tf(
        tmp_path / "joinLeft.tf",
        "@edge\n@description=left relation\n@valueType=str",
        "10\t20\n",
    )
    h = fd().read_header(path)
    assert h.kind == "edge"
    assert h.valued is False


def test_edge_values_marker_makes_edge_valued(tmp_path):
    path = write_tf(
        tmp_path / "joined.tf",
        "@edge\n@edgeValues\n@description=join relation\n@valueType=str",
        "10\t20\tdirect\n",
    )
    h = fd().read_header(path)
    assert h.kind == "edge"
    assert h.valued is True


def test_header_reader_stops_before_feature_body():
    class ExplodingStream:
        def __init__(self):
            self.lines = iter(("@node\n", "@description=test\n", "\n"))

        def __enter__(self):
            return self

        def __exit__(self, *_args):
            return False

        def __iter__(self):
            return self

        def __next__(self):
            try:
                return next(self.lines)
            except StopIteration:
                raise AssertionError("feature body was read")

    class FakePath:
        def open(self, **_kwargs):
            return ExplodingStream()

        def __str__(self):
            return "exploding.tf"

    assert fd().read_header(FakePath()).metadata["description"] == "test"


def test_discovery_classifies_warp_and_optional_provenance(tmp_path):
    core = tmp_path / "tf"
    prov = tmp_path / "prov"
    core.mkdir()
    prov.mkdir()
    write_tf(core / "otype.tf", "@node\n@valueType=str")
    write_tf(core / "lemma.tf", "@node\n@description=lexical lemma\n@valueType=str")
    write_tf(prov / "srcxml.tf", "@node\n@description=source XML\n@valueType=str")

    features = fd().discover_features(
        core,
        provenance_dir=prov,
        descriptions={"lemma": "lexical lemma", "srcxml": "source XML"},
    )
    by_name = {feature.name: feature for feature in features}
    assert by_name["otype"].kind == "infrastructure"
    assert by_name["otype"].module == "core"
    assert by_name["srcxml"].module == "provenance"
    assert by_name["srcxml"].optional is True


def test_description_drift_fails_discovery(tmp_path):
    core = tmp_path / "tf"
    core.mkdir()
    write_tf(core / "lemma.tf", "@node\n@description=stale text\n@valueType=str")

    with pytest.raises(fd().FeatureDocsError, match="lemma.*description"):
        fd().discover_features(core, descriptions={"lemma": "lexical lemma"})


def test_render_tree_contains_every_discovered_feature(tmp_path):
    core = tmp_path / "tf"
    prov = tmp_path / "prov"
    core.mkdir()
    prov.mkdir()
    write_tf(core / "lemma.tf", "@node\n@description=lexical lemma\n@valueType=str\n@version=1")
    write_tf(core / "joined.tf", "@edge\n@edgeValues\n@description=joins\n@valueType=str\n@version=1")
    write_tf(prov / "srcxml.tf", "@node\n@description=source XML\n@valueType=str\n@version=1")

    features = fd().discover_features(
        core,
        provenance_dir=prov,
        descriptions={"lemma": "lexical lemma", "joined": "joins", "srcxml": "source XML"},
    )
    tree = fd().render_tree(features, version="1")
    assert set(tree) == {"0_home.md", "lemma.md", "joined.md", "srcxml.md"}
    assert "optional provenance" in tree["0_home.md"].lower()
    assert "not loaded by default" in tree["srcxml.md"].lower()


def test_check_tree_detects_missing_stale_and_unexpected_generated_pages(tmp_path):
    out = tmp_path / "features"
    out.mkdir()
    (out / "lemma.md").write_text("old", encoding="utf8")
    (out / "obsolete.md").write_text(
        "<!-- generated by TLHdig-TF featuredocs; do not edit -->\nold\n",
        encoding="utf8",
    )
    expected = {
        "0_home.md": "home\n",
        "lemma.md": "new\n",
    }
    problems = fd().check_tree(out, expected)
    assert any("0_home.md" in p and "missing" in p for p in problems)
    assert any("lemma.md" in p and "stale" in p for p in problems)
    assert any("obsolete.md" in p and "unexpected" in p for p in problems)


def test_check_tree_detects_broken_internal_markdown_links(tmp_path):
    out = tmp_path / "features"
    out.mkdir()
    expected = {
        "0_home.md": "[missing feature](missing.md)\n",
        "lemma.md": "[home](0_home.md)\n",
    }
    fd().write_tree(out, expected)

    problems = fd().check_tree(out, expected)
    assert any(
        "0_home.md" in problem
        and "missing.md" in problem
        and "broken internal link" in problem
        for problem in problems
    )


def test_shipped_app_has_explicit_working_feature_doc_template():
    root = Path(__file__).resolve().parents[2]
    config = yaml.safe_load((root / "app" / "config.yaml").read_text(encoding="utf8"))
    docs = config["docs"]
    assert docs["featureBase"] == "{docBase}/docs/features/<feature>{docExt}"
    assert docs["featurePage"] == "0_home"

    landing = docs["featureBase"].replace("<feature>", docs["featurePage"])
    assert landing == "{docBase}/docs/features/0_home{docExt}"
    assert (root / "docs" / "features" / "0_home.md").is_file()


def test_shipped_generated_reference_covers_release_and_optional_module():
    root = Path(__file__).resolve().parents[2]
    core = root / "tf" / TF_VERSION
    provenance = root / "tf-provenance" / TF_VERSION
    if not core.is_dir():
        pytest.skip("current TF release is not present")

    expected_names = {p.stem for p in core.glob("*.tf")}
    expected_names |= {p.stem for p in provenance.glob("*.tf")}
    pages = {p.stem for p in (root / "docs" / "features").glob("*.md")}
    assert expected_names <= pages
    assert "0_home" in pages


def test_text_fabric_normalizes_local_app_feature_doc_links_without_loading_data():
    """Exercise TF 13.1's real settings parser without paying the 5 GB load cost."""
    from tf.app import use

    root = Path(__file__).resolve().parents[2]
    app = use(f"app:{(root / 'app').resolve()}", loadData=False, silent="deep")
    assert app is not None
    assert app.context.featureBase == (
        "https://github.com/alexsosn/TLHdig-TF/blob/main/docs/features/"
        "<feature>.md"
    )
    assert app.context.featurePage == "0_home"
    assert app.context.docUrl == (
        "https://github.com/alexsosn/TLHdig-TF/blob/main/README.md"
    )
