"""Preservation guard: ordinary Python cache files are not release inputs."""
from __future__ import annotations

from pathlib import Path
import subprocess
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tlhdig import protected_tree


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=root, check=True, text=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    return result.stdout.strip()


def test_ignored_pycache_does_not_self_invalidate_release_identity(tmp_path):
    root = tmp_path / "repo"
    root.mkdir()
    _git(root, "init")
    _git(root, "config", "user.name", "Pycache Fixture")
    _git(root, "config", "user.email", "pycache@example.invalid")
    for rel, text in (
        ("programs/checker.py", "VALUE = 1\n"),
        ("corpus/a.xml", "<a/>\n"),
        ("app/config.yaml", "version: one\n"),
        ("requirements.txt", "text-fabric==13.1.0\n"),
        (".github/workflows/certify-dataset.yml", "name: certify\n"),
        (".gitignore", "__pycache__/\n*.py[cod]\n"),
    ):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf8")
    _git(root, "add", "-A")
    _git(root, "commit", "-m", "fixture")

    baseline = protected_tree.identity(root)
    cache = root / "programs" / "__pycache__" / "checker.cpython-313.pyc"
    cache.parent.mkdir()
    cache.write_bytes(b"generated bytecode placeholder")
    assert _git(root, "check-ignore", cache.relative_to(root).as_posix())

    assert protected_tree.identity(root) == baseline
