"""Per-feature descriptions.

These become the `@description` lines in the .tf files and the source for
docs/features.md, so they are the corpus's own documentation.  Where upstream
semantics are unconfirmed (plan §11) the description says so rather than implying
more certainty than exists.
"""

DESCRIPTIONS = {
    # ---- sign
    "srcxml": "verbatim source fragment of this sign, inline markers at their true offsets",
    "sym": "clean reading of the sign, markers stripped",
    "after": "separator between this sign and the next ('-', '.', ' ' or empty)",
    "type": "kind of token: reading | signname | numeral | unknown | ellipsis | empty",
    "sgr": "1 if the sign lies inside a Sumerogram <sGr>",
    "agr": "1 if the sign lies inside an Akkadogram <aGr>",
    "det": "1 if the sign lies inside a determinative <d>",
    "num": "1 if the sign lies inside a numeral <num>",
    "missing": "1 if the sign lies inside a lacuna (del_in/del_fin)",
    "laes": "1 if the sign lies inside a damaged-but-legible range (laes_in/laes_fin)",
    "ras": "1 if the sign lies inside an erasure (ras_in/ras_fin)",
    "add": "1 if the sign lies inside an editorial addition (add_in/add_fin)",
    "quot": "1 if the sign lies inside a Hurrian quotation",
    "corr": "philological mark on the sign: ?, !, sic, ...",
    "subscr": "epigraphically subscripted sign attached to this one (not a reading index)",
    "materlect": "mater lectionis / explanatory additional sign",
    "materlect_anomalous": "1 when materlect holds a bare ! or ? (mis-styled legacy data)",
    "surplus": "superfluous sign written by the scribe and excised by the editor",
    "space_count": "number of U+0020 SPACE characters before this sign (ODF text:s/@text:c)",
    # ---- word
    "trans": "normalised transliteration used as the lookup key (@trans)",
    "mrpsel": "raw mrp0sel disambiguation pointer",
    "mrpsel_kind": "analysis | none | unknown | DEL | AKK | HURR | HAT | SUM | LUW",
    "sel_base": "selected base alternative letter(s), lower case",
    "sel_clitic": "selected clitic alternative letter(s), upper case (reverse-engineered)",
    "sel_group": "group selector: all | sg | pl (sg/pl not formally documented upstream)",
    "nanalyses": "number of candidate morphological analyses on this word",
    # ---- analysis
    "index": "the N of the mrpN attribute; the index space starts at 0 and has gaps",
    "raw": "the mrpN value verbatim; stored only when parse_ok=0, otherwise recoverable via the word's src_span",
    "sep": "which clitic separator form the value used (+=, @+=, +@, @+@)",
    "parse_ok": "0 when the mrp value did not match the documented grammar",
    "lemma": "citation form of the base lemma",
    "gloss": "German gloss of the base lemma",
    "morph": "morphological tag, or a lettered set of alternatives",
    "stemclass": "Stammklasse / paradigm number, when field 4 holds one",
    "stemclass_raw": "field 4 verbatim, before the three-way disambiguation",
    "field4_kind": "how field 4 was read: stemclass | pos | morph | empty",
    "pos": "part of speech, when field 4 holds a closed-vocabulary category",
    "det_hint": "determinative / classifier expected with the lemma",
    "clitic_lemma": "lemma of the enclitic, when present",
    "clitic_morph": "morphological tag of the enclitic",
    "clitic_stemclass": "stem-class slot of the enclitic (usually empty)",
    "clitic_det": "determinative field carried on the clitic segment",
    # ---- line / column / surface
    "lnr": "raw lb/@lnr line reference",
    "lnno": "citation form of the line within its column",
    "ln": "numeric part of the line reference",
    "prime": "prime marker: relative numbering on a broken tablet",
    "linetail": "trailing part of the line reference (a, b, /1', ...)",
    "txtid": "manuscript siglum for this line (lb/@txtid)",
    "cu": "Unicode cuneiform for the whole line; not sign-aligned",
    "cudirty": "lb/@cuDirty flag",
    "cu_broken": "count of U+2592 placeholders for illegible signs in cu",
    "cu_pua": "count of Private Use Area codepoints in cu",
    "srcln": "ordinal of this line within its document",
    "column": "column designation (I, II, lk. Kol., ...)",
    "collabel": "level-2 section label: fragment + surface + column, unique per document",
    "frag": "fragment/witness siglum in scope for this column",
    "surface": "obverse/reverse/edge designation",
    "ruling": "paragraph ruling: single | double",
    # ---- colon / edit / document
    "id": "clb/@id, sequential within the document",
    "nr": "clb/@nr",
    "kind": "kind of editorial event (kor, kor2, uebern, annot, ...)",
    "editor": "editor initials or name recorded on the event",
    "date": "timestamp recorded on the event",
    "part": "part of the document the event applies to",
    "src": "source the transliteration was taken over from",
    "frgm": "fragment the event applies to",
    "docs": "documents involved in a merge event",
    "comment": "free-text comment on the event",
    "author": "author recorded on an <author> event",
    "alt": "previous CTH number (cth/@alt)",
    "neu": "new CTH number (cth/@neu)",
    "order": "position of the event within <meta>",
    "docid": "document identifier, verbatim from <docID>. NOT unique: 141 values are shared by more than one document node, so a (docid, ...) section address can be ambiguous. The planned docgroup layer is not implemented.",
    "docid_raw": "the <docID> element verbatim",
    "cth": "CTH catalogue number, from the containing directory",
    "subcorpus": "HPM sub-project, from the containing directory (TLH, HFR, ...)",
    "src_file": "path of the source XML relative to the corpus root",
    "lang": "language; omitted entirely when the source says XXXlang (= unset)",
    "lang_raw": "the language token verbatim, including XXXlang",
    "anchor": "1 on an artificial slot created so a document with no readable sign survives",
    # ---- cluster
    "orphan": "none | open | close -- whether the range's partner marker is absent",
    "start_offset": "character offset of the opening marker within its sign",
    "end_offset": "character offset of the closing marker within its sign",
    "crossesline": "1 when the range continues across a line boundary",
    "nested": "1 when a second open of the same family was already active",
    # ---- layout
    "markers": "marker tags carried by a contentless <w>, space separated",
    "src_span": "byte range of the source element. WARNING: for the 166 repaired documents whose patches change length, this indexes the repaired byte stream, not the file named by src_file. See KNOWN-ISSUES.md.",
    # ---- edges
    "analyses": "word -> every candidate morphological analysis",
    "selected": "word -> the analysis mrp0sel points at; value is the alternative letter",
    "edits": "editorial event -> the document it applies to",
    "oslots": "TF warp: node -> the slots it covers",
}
