"""Generate the app-facing feature reference from shipped Text-Fabric headers.

The release artifact, not a conversion plan, is the inventory authority.  This module
therefore reads only the metadata header of each shipped ``.tf`` file, validates its
semantic description against :mod:`tlhdig.featuremeta`, and renders deterministic
Markdown.  Feature bodies can be tens of megabytes and are deliberately never read.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping

from .featuremeta import DESCRIPTIONS

GENERATED_MARKER = "<!-- generated by TLHdig-TF featuredocs; do not edit -->"

# Text-Fabric warp/config files are infrastructure, not TLHdig scholarly annotations.
# They are the only descriptions maintained here because they are TF concepts rather
# than corpus feature semantics governed by featuremeta.DESCRIPTIONS.
INFRASTRUCTURE_DESCRIPTIONS = {
    "otype": "Text-Fabric warp feature mapping every node to its node type.",
    "oslots": "Text-Fabric warp edge mapping every non-slot node to the slots it covers.",
    "otext": "Text-Fabric configuration for section levels, section features, and text formats.",
}

STABLE_METADATA = (
    ("valueType", "Value type"),
    ("version", "TF artifact version"),
    ("sourceVersion", "Source version"),
    ("sourceDoi", "Source DOI"),
    ("sourceLicense", "Source license"),
    ("license", "Feature license"),
    ("attribution", "Attribution"),
)


class FeatureDocsError(ValueError):
    """A shipped feature header cannot be documented without ambiguity."""


@dataclass(frozen=True)
class Header:
    """Structured metadata from the header of one Text-Fabric feature file."""

    kind: str
    valued: bool
    metadata: dict[str, str]
    markers: frozenset[str]


@dataclass(frozen=True)
class FeatureDoc:
    """Stable documentation facts for one shipped feature."""

    name: str
    module: str
    kind: str
    valued: bool
    optional: bool
    description: str
    metadata: dict[str, str]
    path: Path


def read_header(path: Path) -> Header:
    """Read and classify only the metadata header of ``path``.

    The first blank line is the hard boundary.  In particular, this function must not
    inspect a feature body in order to infer whether an edge is valued: Text-Fabric
    declares that with ``@edgeValues`` in the header.
    """

    markers: set[str] = set()
    metadata: dict[str, str] = {}

    try:
        stream = path.open(encoding="utf8")
    except OSError as exc:
        raise FeatureDocsError(f"{path}: cannot read feature header: {exc}") from exc

    with stream:
        for raw in stream:
            line = raw.rstrip("\r\n")
            if not line:
                break
            if not line.startswith("@"):
                raise FeatureDocsError(
                    f"{path}: malformed feature header line before blank boundary: {line!r}"
                )
            item = line[1:]
            if "=" in item:
                key, value = item.split("=", 1)
                if not key:
                    raise FeatureDocsError(f"{path}: empty metadata key")
                metadata[key] = value
            else:
                markers.add(item)

    primary = [kind for kind in ("node", "edge", "config") if kind in markers]
    if len(primary) != 1:
        raise FeatureDocsError(
            f"{path}: expected exactly one of @node, @edge, @config; found {primary!r}"
        )
    if "edgeValues" in markers and primary[0] != "edge":
        raise FeatureDocsError(f"{path}: @edgeValues without @edge")

    return Header(
        kind=primary[0],
        valued="edgeValues" in markers,
        metadata=metadata,
        markers=frozenset(markers),
    )


def _one_feature(
    path: Path,
    *,
    module: str,
    optional: bool,
    descriptions: Mapping[str, str],
) -> FeatureDoc:
    name = path.stem
    header = read_header(path)

    if name in INFRASTRUCTURE_DESCRIPTIONS:
        return FeatureDoc(
            name=name,
            module=module,
            kind="infrastructure",
            valued=header.valued,
            optional=optional,
            description=header.metadata.get("description")
            or INFRASTRUCTURE_DESCRIPTIONS[name],
            metadata=header.metadata,
            path=path,
        )

    shipped_description = header.metadata.get("description", "").strip()
    if not shipped_description:
        raise FeatureDocsError(f"{name}: shipped feature has no @description")

    canonical = descriptions.get(name)
    if canonical is None:
        raise FeatureDocsError(
            f"{name}: released feature has no canonical description in featuremeta.DESCRIPTIONS"
        )
    if shipped_description != canonical:
        raise FeatureDocsError(
            f"{name}: shipped @description differs from canonical description"
        )

    if header.kind == "config":
        raise FeatureDocsError(f"{name}: non-infrastructure feature unexpectedly uses @config")

    return FeatureDoc(
        name=name,
        module=module,
        kind=header.kind,
        valued=header.valued,
        optional=optional,
        description=shipped_description,
        metadata=header.metadata,
        path=path,
    )


def discover_features(
    core_dir: Path,
    *,
    provenance_dir: Path | None = None,
    descriptions: Mapping[str, str] = DESCRIPTIONS,
) -> list[FeatureDoc]:
    """Discover the released core and optional provenance feature files."""

    if not core_dir.is_dir():
        raise FeatureDocsError(f"core feature directory does not exist: {core_dir}")

    found: list[FeatureDoc] = []
    for path in sorted(core_dir.glob("*.tf"), key=lambda p: p.name):
        found.append(
            _one_feature(
                path,
                module="core",
                optional=False,
                descriptions=descriptions,
            )
        )

    if provenance_dir is not None and provenance_dir.is_dir():
        for path in sorted(provenance_dir.glob("*.tf"), key=lambda p: p.name):
            if any(feature.name == path.stem for feature in found):
                raise FeatureDocsError(
                    f"{path.stem}: feature name occurs in both core and provenance modules"
                )
            found.append(
                _one_feature(
                    path,
                    module="provenance",
                    optional=True,
                    descriptions=descriptions,
                )
            )

    return found


def _kind_label(feature: FeatureDoc) -> str:
    if feature.kind == "infrastructure":
        return "Text-Fabric infrastructure/configuration"
    if feature.kind == "edge" and feature.valued:
        return "valued edge feature"
    if feature.kind == "edge":
        return "edge feature"
    return "node feature"


def _render_feature(feature: FeatureDoc) -> str:
    lines = [
        GENERATED_MARKER,
        f"# `{feature.name}`",
        "",
        "[Feature reference](0_home.md)",
        "",
        f"**Module:** {feature.module}",
        "",
        f"**Kind:** {_kind_label(feature)}",
        "",
    ]
    if feature.optional:
        lines.extend(
            [
                "**Availability:** optional provenance module; not loaded by default.",
                "",
            ]
        )
    lines.extend(["## Description", "", feature.description, "", "## Release metadata", ""])

    emitted = False
    for key, label in STABLE_METADATA:
        value = feature.metadata.get(key)
        if value:
            lines.append(f"- **{label}:** {value}")
            emitted = True
    if not emitted:
        lines.append("- No additional stable release metadata is declared in the header.")

    module_path = "tf-provenance" if feature.module == "provenance" else "tf"
    version = feature.metadata.get("version", "<version>")
    lines.extend(
        [
            "",
            "---",
            "",
            (
                "Generated from the shipped Text-Fabric header at "
                f"`{module_path}/{version}/{feature.name}.tf`; corpus feature semantics "
                "are checked against `programs/tlhdig/featuremeta.py`."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def _group(features: Iterable[FeatureDoc], predicate) -> list[FeatureDoc]:
    return sorted((feature for feature in features if predicate(feature)), key=lambda f: f.name)


def render_tree(features: Iterable[FeatureDoc], *, version: str) -> dict[str, str]:
    """Render the complete deterministic ``docs/features`` tree in memory."""

    features = list(features)
    tree = {f"{feature.name}.md": _render_feature(feature) for feature in features}

    groups = (
        (
            "Core node features",
            _group(features, lambda f: f.module == "core" and f.kind == "node"),
        ),
        (
            "Core edge features",
            _group(
                features,
                lambda f: f.module == "core" and f.kind == "edge" and not f.valued,
            ),
        ),
        (
            "Core valued-edge features",
            _group(
                features,
                lambda f: f.module == "core" and f.kind == "edge" and f.valued,
            ),
        ),
        (
            "Text-Fabric infrastructure/configuration",
            _group(features, lambda f: f.module == "core" and f.kind == "infrastructure"),
        ),
        (
            "Optional provenance features",
            _group(features, lambda f: f.module == "provenance"),
        ),
    )

    lines = [
        GENERATED_MARKER,
        "# Feature reference",
        "",
        f"Generated from the shipped Text-Fabric **{version}** release.",
        "",
        (
            "The core sections describe files loaded from the main `tf` release. "
            "Optional provenance features are distributed separately and are **not "
            "loaded by default**."
        ),
        "",
    ]
    for title, members in groups:
        lines.extend([f"## {title}", ""])
        if not members:
            lines.extend(["_None._", ""])
            continue
        for feature in members:
            suffix = " — optional provenance" if feature.optional else ""
            lines.append(f"- [`{feature.name}`]({feature.name}.md){suffix}")
        lines.append("")

    tree["0_home.md"] = "\n".join(lines)
    return dict(sorted(tree.items()))


def check_tree(output_dir: Path, expected: Mapping[str, str]) -> list[str]:
    """Return deterministic drift problems without modifying ``output_dir``."""

    problems: list[str] = []
    for name, content in sorted(expected.items()):
        path = output_dir / name
        if not path.is_file():
            problems.append(f"{name}: missing generated feature documentation")
            continue
        try:
            actual = path.read_text(encoding="utf8")
        except OSError as exc:
            problems.append(f"{name}: cannot read generated documentation: {exc}")
            continue
        if actual != content:
            problems.append(f"{name}: stale generated feature documentation")

    if output_dir.is_dir():
        for path in sorted(output_dir.glob("*.md"), key=lambda p: p.name):
            if path.name in expected:
                continue
            try:
                text = path.read_text(encoding="utf8")
            except OSError as exc:
                problems.append(f"{path.name}: cannot read unexpected page: {exc}")
                continue
            if GENERATED_MARKER in text:
                problems.append(f"{path.name}: unexpected stale generated page")

    return problems


def write_tree(output_dir: Path, expected: Mapping[str, str]) -> None:
    """Write expected pages and remove only obsolete pages carrying our marker."""

    output_dir.mkdir(parents=True, exist_ok=True)
    for name, content in sorted(expected.items()):
        (output_dir / name).write_text(content, encoding="utf8")

    for path in sorted(output_dir.glob("*.md"), key=lambda p: p.name):
        if path.name in expected:
            continue
        try:
            text = path.read_text(encoding="utf8")
        except OSError:
            continue
        if GENERATED_MARKER in text:
            path.unlink()
