"""Per-feature descriptions.

These become the `@description` lines in the .tf files and the source for
docs/features.md, so they are the corpus's own documentation.  Where upstream
semantics are unconfirmed (plan §11) the description says so rather than implying
more certainty than exists.
"""

DESCRIPTIONS = {
    # ---- sign
    "srcxml": "verbatim source fragment of this sign, inline markers at their true offsets",
    "sym": "clean reading of the sign, markers stripped",
    "after": "separator between this sign and the next ('-', '.', ' ' or empty)",
    "type": "kind of token: reading | signname | numeral | unknown | ellipsis | empty",
    "sgr": "1 if the sign lies inside a Sumerogram <sGr>",
    "agr": "1 if the sign lies inside an Akkadogram <aGr>",
    "det": "1 if the sign lies inside a determinative <d>",
    "num": "1 if the sign lies inside a numeral <num>",
    "missing": "1 if the sign lies inside a lacuna (del_in/del_fin)",
    "laes": "1 if the sign lies inside a damaged-but-legible range (laes_in/laes_fin)",
    "ras": "1 if the sign lies inside an erasure (ras_in/ras_fin)",
    "add": "1 if the sign lies inside an editorial addition (add_in/add_fin)",
    "quot": "1 if the sign lies inside a Hurrian quotation",
    "corr": "philological mark on the sign: ?, !, sic, ...",
    "subscr": "epigraphically subscripted sign attached to this one (not a reading index)",
    "materlect": "mater lectionis / explanatory additional sign",
    "materlect_anomalous": "1 when materlect holds a bare ! or ? (mis-styled legacy data)",
    "surplus": "superfluous sign written by the scribe and excised by the editor",
    "othertags": "inline elements inside this sign that have no dedicated feature, space separated (ras_X, AkkGLOS, HitGLOS, PARSER_ERROR, del_iin, leaked ODF styling). Their text is already in `sym`; this records the tag identity, so `srcxml` is not the sole record of anything. 149 signs carry one.",
    "cu_sign": "the cuneiform for this sign, where the line aligned (see `cu_aligned`). Usually one codepoint; a compound logogram such as MEŠ = 𒈨𒌍 carries the whole sequence, and `cu_nsigns` then says how many. Absent means unknown, not 'no sign'.",
    "cu_nsigns": "number of cuneiform codepoints in `cu_sign`, present only when more than one. A grapheme query must match within `cu_sign`, not equal it, for these.",
    "symmark": "editorial marks that were written inside this sign's reading and are not part of the sign: `()` uncertain word division, `〈〉` editorial insertion, `˽` a spacing mark. Removed from `sym` so it is a clean reading; kept here verbatim.",
    "space_count": "number of U+0020 SPACE characters before this sign (ODF text:s/@text:c)",
    # ---- word
    "trans": "normalised transliteration used as the lookup key (@trans)",
    "mrpsel": "raw mrp0sel disambiguation pointer",
    "mrpsel_kind": "analysis | none | unknown | DEL | AKK | HURR | HAT | SUM | LUW",
    "sel_base": "selected base alternative letter(s), lower case",
    "sel_clitic": "selected clitic alternative letter(s), upper case (reverse-engineered)",
    "sel_group": "group selector: all | sg | pl (sg/pl not formally documented upstream)",
    "nanalyses": "number of candidate morphological analyses on this word",
    "nselected": "number of distinct analyses mrp0sel points at; >1 on 7,290 words, where the editor selected several",
    # ---- analysis
    "index": "the N of the mrpN attribute; the index space starts at 0 and has gaps",
    "raw": "the mrpN value verbatim. Stored when the parsed fields do not reconstruct it: parse_ok=0, or the source padded a field with spaces and normalisation stripped it. Absent means lemma/gloss/morph/det reconstruct the source exactly.",
    "sep": "which clitic separator form the value used (+=, @+=, +@, @+@)",
    "parse_ok": "0 when the mrp value did not match the documented grammar",
    "lemma": "citation form of the base lemma, whitespace-stripped. Padding split 3,018 of 28,180 distinct lemmas into duplicates -- 10.7% of the lexicon. See `raw`.",
    "gloss": "German gloss of the base lemma, whitespace-stripped. The source pads fields (`@ gehen@`); left verbatim it split 916 of 8,550 distinct glosses into duplicates. See `raw`.",
    "morph": "morphological tag, or a lettered set of alternatives",
    "stemclass": "Stammklasse / paradigm number, when field 4 holds one",
    "stemclass_raw": "field 4 verbatim, before the three-way disambiguation",
    "field4_kind": "how field 4 was read: stemclass | pos | morph | empty",
    "pos": "part of speech, when field 4 holds a closed-vocabulary category",
    "det_hint": "determinative / classifier expected with the lemma",
    "clitic_lemma": "lemma of the enclitic, when present",
    "clitic_morph": "morphological tag of the enclitic",
    "clitic_stemclass": "stem-class slot of the enclitic (usually empty)",
    "clitic_det": "determinative field carried on the clitic segment",
    # ---- line / column / surface
    "lnr": "raw lb/@lnr line reference",
    "lnno": "citation form of the line within its column",
    "ln": "numeric part of the line reference",
    "prime": "prime marker: relative numbering on a broken tablet",
    "linetail": "trailing part of the line reference (a, b, /1', ...)",
    "txtid": "manuscript siglum for this line (lb/@txtid)",
    "cu": "Unicode cuneiform for the whole line; not sign-aligned. Use `cu_sign` on the sign for the aligned form.",
    "cu_aligned": "how this line's cuneiform was laid out per sign: 0 not aligned, 1 counts matched and were zipped, 2 aligned after absorbing surplus U+2592 placeholders into a recorded lacuna, 3 aligned after expanding a compound logogram, 4 aligned using the derived numeral rule. Higher numbers are weaker evidence, so a query wanting only the safest material filters cu_aligned=1.",
    "cudirty": "lb/@cuDirty flag",
    "cu_broken": "count of U+2592 placeholders for illegible signs in cu",
    "cu_pua": "count of Private Use Area codepoints in cu",
    "srcln": "ordinal of this line within its document",
    "column": "column designation (I, II, lk. Kol., ...)",
    "collabel": "level-2 section label: fragment + surface + column, unique per document",
    "frag": "fragment/witness siglum in scope for this column",
    "surface": "obverse/reverse/edge designation",
    "ruling": "paragraph ruling: single | double",
    # ---- colon / edit / document
    "id": "clb/@id, sequential within the document",
    "nr": "clb/@nr",
    "kind": "kind of editorial event (kor, kor2, uebern, annot, ...)",
    "editor": "editor initials or name recorded on the event",
    "date": "timestamp recorded on the event",
    "part": "part of the document the event applies to",
    "src": "source the transliteration was taken over from",
    "frgm": "fragment the event applies to",
    "docs": "documents involved in a merge event",
    "comment": "free-text comment on the event",
    "author": "author recorded on an <author> event",
    "alt": "previous CTH number (cth/@alt)",
    "neu": "new CTH number (cth/@neu)",
    "order": "position of the event within <meta>",
    "docid": "document identifier, from <docID>, whitespace-stripped. NOT unique: 141 values are shared by more than one document node, so a (docid, ...) section address can be ambiguous. `docgroup` nodes group the records that share one, but section addressing itself is still ambiguous.",
    "docid_raw": "same value as `docid` today: the converter strips both. Kept as a distinct feature so a future build can carry the unstripped element without a schema change.",
    "cth": "CTH catalogue number, from the containing directory",
    "subcorpus": "HPM sub-project, from the containing directory (TLH, HFR, ...)",
    "src_file": "path of the source XML relative to the corpus root",
    "lang": "language; omitted entirely when the source says XXXlang (= unset)",
    "lang_raw": "the language token verbatim, including XXXlang",
    "anchor": "1 on an artificial slot created so a document with no readable sign survives",
    # ---- cluster
    "width": "number of signs the range encloses; 0 marks a point break, which anchors "
             "to its boundary sign but does not flag it as damaged",
    "orphan": "none | open | close -- whether the range's partner marker is absent",
    "start_offset": "character offset of the opening marker within its sign",
    "end_offset": "character offset of the closing marker within its sign",
    "crossesline": "1 when the range continues across a line boundary",
    "nested": "1 when a second open of the same family was already active",
    # ---- layout
    "markers": "marker tags carried by a contentless <w>, space separated",
    "src_span": "byte range of the source element. WARNING: for the 166 repaired documents whose patches change length, this indexes the repaired byte stream, not the file named by src_file. See KNOWN-ISSUES.md.",
    "nrecords": "number of document records that claim this manuscript identity",
    "txtpubl": "publication siglum of a constituent manuscript",
    "invnr": "excavation / inventory numbers recorded for the document",
    "directjoin": "manuscripts joined directly to this one",
    "indirectjoin": "manuscripts joined indirectly to this one",
    "n": "footnote number",
    "c": "footnote content, as escaped rich text in the source",
    # ---- lex
    "noccs": "number of analyses that resolve to this lexeme",
    # ---- edges
    "lexeme": "analysis -> the lex node for its (lemma, gloss). The lex node's oslots is an ANCHOR, one slot of its first occurrence, not its extent: a lexeme's attestations are scattered, so containment must be read through this edge, never off slots.",
    "analyses": "word -> every candidate morphological analysis",
    "selected": "word -> an analysis mrp0sel points at; value is the selector token(s) that chose it, verbatim (`1`, `2a`, `1bR 1bS`). A word can have several: 7,290 select more than one analysis. Never empty -- a valued TF edge feature must not mix values with None.",
    "edits": "editorial event -> the document it applies to",
    "from_open_marker": "1 when the range's start is a real source marker rather than a "
                        "bound synthesised from a line start",
    "from_close_marker": "1 when the range's end is a real source marker rather than a "
                         "bound synthesised from the line end, document end, or a reopen",
    "startsAt": "cluster -> the sign its opening boundary counts into (see start_offset). "
                "Not always covered by oslots: a marker at len(sym) sits after its sign.",
    "endsAt": "cluster -> the sign its closing boundary counts into (see end_offset)",
    "witness": "line -> the fragment(s) it is attested on; many-to-many, since an lnr "
               "siglum may be composite (EUR1+2)",
    "noteref": "note -> the sign it is anchored to",
    "edition": "document -> the docgroup of records claiming the same manuscript",
    "oslots": "TF warp: node -> the slots it covers",
}
