#!/usr/bin/env python
"""Inventory TLHdig source-path structure for one or more corpus releases.

Usage:
    python programs/analyze_source_paths.py LABEL=PATH [LABEL=PATH ...]

Each PATH may point at a corpus root or an extracted archive with arbitrary wrapper
folders above it.  The analyser deliberately separates observed path structure from
interpretation: only the stable ``CTH <n>_XML`` prefix and the optional 0.3-style
``_<project>`` suffix are parsed; intermediate directory names are retained verbatim.
"""
from __future__ import annotations

import hashlib
import html
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

# Beta 0.2 uses ``CTH 241_XML``.  Beta 0.3 uses e.g. ``CTH 241_XML_TLH``.
TOP_RE = re.compile(r"^CTH ([^_]+)_XML(?:_(.+))?$")
DOCID_RE = re.compile(br"<docID>(.*?)</docID>", re.DOTALL)
NESTED_SUFFIX_RE = re.compile(r"_([A-Za-z][A-Za-z0-9]*)$")


@dataclass(frozen=True)
class Record:
    release: str
    rel: str
    top_dir: str
    cth: str
    project: str
    subdir: str
    stem: str
    docid: str
    sha256: str


def _find_root(path: Path) -> Path:
    """Find the unique real directory whose immediate children are CTH corpus dirs."""
    candidates: list[Path] = []
    for current, dirs, _files in os.walk(path):
        current_path = Path(current)
        # Finder/resource-fork metadata in the 0.2 ZIP mirrors the directory tree under
        # __MACOSX.  It is archive packaging, not a second corpus root.
        if "__MACOSX" in current_path.parts:
            dirs[:] = []
            continue
        dirs[:] = [d for d in dirs if d != "__MACOSX"]
        if any(TOP_RE.match(name) for name in dirs):
            candidates.append(current_path)
            # A corpus root can contain nested CTH-like shard names.  Once a candidate
            # root is found, do not descend into it while searching for more roots.
            dirs[:] = []
    if len(candidates) != 1:
        shown = ", ".join(str(p) for p in candidates[:5]) or "none"
        raise ValueError(
            f"cannot identify a unique corpus root below {path}: "
            f"{len(candidates)} candidates ({shown})"
        )
    return candidates[0]


def _docid(data: bytes) -> str:
    """Read docID without requiring the whole source file to be well-formed XML."""
    m = DOCID_RE.search(data)
    if not m:
        return ""
    return html.unescape(m.group(1).decode("utf-8", errors="replace")).strip()


def scan(label: str, base: Path) -> list[Record]:
    root = _find_root(base)
    out: list[Record] = []
    for path in sorted(root.rglob("*.xml")):
        rel = path.relative_to(root).as_posix()
        parts = PurePosixPath(rel).parts
        m = TOP_RE.match(parts[0]) if parts else None
        cth, project = (m.group(1), m.group(2) or "") if m else ("", "")
        data = path.read_bytes()
        out.append(
            Record(
                release=label,
                rel=rel,
                top_dir=parts[0] if parts else "",
                cth=cth,
                project=project,
                subdir="/".join(parts[1:-1]),
                stem=path.stem,
                docid=_docid(data),
                sha256=hashlib.sha256(data).hexdigest(),
            )
        )
    return out


def _table(rows: list[tuple[str, ...]]) -> list[str]:
    if not rows:
        return []
    return [
        "| " + " | ".join(rows[0]) + " |",
        "|" + "|".join("---" for _ in rows[0]) + "|",
        *("| " + " | ".join(r) + " |" for r in rows[1:]),
    ]


def _top_grammar(recs: list[Record]) -> Counter[str]:
    result: Counter[str] = Counter()
    for r in recs:
        if not r.cth:
            result["unmatched"] += 1
        elif r.project:
            result["CTH <n>_XML_<project>"] += 1
        else:
            result["CTH <n>_XML"] += 1
    return result


def _nested_suffixes(recs: list[Record]) -> Counter[str]:
    result: Counter[str] = Counter()
    for r in recs:
        for component in PurePosixPath(r.subdir).parts if r.subdir else ():
            m = NESTED_SUFFIX_RE.search(component)
            if m:
                result[m.group(1)] += 1
    return result


def report(releases: dict[str, list[Record]]) -> str:
    lines = ["# TLHdig source-path evolution", ""]
    lines += [
        "Generated by `programs/analyze_source_paths.py`. This report inventories path grammar and",
        "cross-release path stability. Nested directory names are reported verbatim unless their",
        "meaning is independently documented.",
        "",
        "## Per-release inventory",
        "",
    ]

    summary = [("release", "XML", "top-level project codes", "path depths", "nested records", "docID != stem")]
    for label, recs in releases.items():
        projects = {r.project for r in recs if r.project}
        depths = sorted({len(PurePosixPath(r.rel).parts) for r in recs})
        nested = sum(bool(r.subdir) for r in recs)
        mismatch = sum(bool(r.docid) and r.docid != r.stem for r in recs)
        summary.append((label, f"{len(recs):,}", str(len(projects)), ", ".join(map(str, depths)), f"{nested:,}", f"{mismatch:,}"))
    lines += _table(summary) + [""]

    for label, recs in releases.items():
        lines += [f"### {label}", "", "#### Top-level grammar", ""]
        grammar = _top_grammar(recs)
        lines += _table([("shape", "documents"), *((f"`{shape}`", f"{n:,}") for shape, n in grammar.most_common())]) + [""]

        proj = Counter(r.project for r in recs if r.project)
        lines += ["#### Top-level project suffixes", ""]
        if proj:
            lines += _table([("project", "documents"), *((f"`{p}`", f"{n:,}") for p, n in proj.most_common())])
        else:
            lines += ["No top-level `_XML_<project>` suffix occurs in this release."]
        lines += [""]

        suffixes = _nested_suffixes(recs)
        lines += ["#### Suffix-like tokens in intermediate directories", ""]
        if suffixes:
            lines += _table([("token", "directory occurrences"), *((f"`{p}`", f"{n:,}") for p, n in suffixes.most_common())])
        else:
            lines += ["No `_TOKEN` suffix was observed on an intermediate directory name."]
        lines += [""]

        sub = Counter(r.subdir for r in recs if r.subdir)
        lines += ["#### Intermediate directory patterns", ""]
        if sub:
            lines += _table([("intermediate path", "documents"), *((f"`{s}`", f"{n:,}") for s, n in sub.most_common(50))])
            if len(sub) > 50:
                lines += ["", f"Only the 50 most frequent of {len(sub):,} distinct intermediate paths are shown."]
        else:
            lines += ["No XML record has an intermediate directory."]
        lines += [""]

    labels = list(releases)
    if len(labels) >= 2:
        lines += ["## Adjacent-release comparisons", ""]
    identity_conclusions: list[str] = []

    for older, newer in zip(labels, labels[1:]):
        a, b = releases[older], releases[newer]
        by_rel_a = {r.rel: r for r in a}
        by_rel_b = {r.rel: r for r in b}
        common_paths = set(by_rel_a) & set(by_rel_b)
        identical_bytes = sum(by_rel_a[p].sha256 == by_rel_b[p].sha256 for p in common_paths)

        doc_a: dict[str, list[Record]] = defaultdict(list)
        doc_b: dict[str, list[Record]] = defaultdict(list)
        for r in a:
            if r.docid:
                doc_a[r.docid].append(r)
        for r in b:
            if r.docid:
                doc_b[r.docid].append(r)
        common_docids = set(doc_a) & set(doc_b)
        same_docid_same_path = sum(
            bool({r.rel for r in doc_a[d]} & {r.rel for r in doc_b[d]}) for d in common_docids
        )
        same_docid_same_stem = sum(
            bool({r.stem for r in doc_a[d]} & {r.stem for r in doc_b[d]}) for d in common_docids
        )
        moved_docids = sorted(
            d for d in common_docids
            if not ({r.rel for r in doc_a[d]} & {r.rel for r in doc_b[d]})
        )

        hash_a: dict[str, list[Record]] = defaultdict(list)
        hash_b: dict[str, list[Record]] = defaultdict(list)
        for r in a:
            hash_a[r.sha256].append(r)
        for r in b:
            hash_b[r.sha256].append(r)
        renamed_identical: list[tuple[set[str], set[str]]] = []
        for h in set(hash_a) & set(hash_b):
            old_paths = {r.rel for r in hash_a[h]}
            new_paths = {r.rel for r in hash_b[h]}
            if old_paths.isdisjoint(new_paths):
                renamed_identical.append((old_paths, new_paths))

        project_codes_a = {r.project for r in a if r.project}
        project_codes_b = {r.project for r in b if r.project}
        old_grammar = _top_grammar(a)
        new_grammar = _top_grammar(b)
        retention = len(common_paths) / len(a) if a else 0.0

        lines += [f"### {older} → {newer}", ""]
        rows = [
            ("measure", "value"),
            ("paths in older", f"{len(a):,}"),
            ("paths in newer", f"{len(b):,}"),
            ("exact paths retained", f"{len(common_paths):,} ({retention:.2%} of older)"),
            ("retained paths with byte-identical XML", f"{identical_bytes:,}"),
            ("docIDs present in both", f"{len(common_docids):,}"),
            ("common docIDs retaining at least one exact path", f"{same_docid_same_path:,}"),
            ("common docIDs retaining at least one filename stem", f"{same_docid_same_stem:,}"),
            ("common docIDs with no exact path retained", f"{len(moved_docids):,}"),
            ("byte-identical records found only at different paths", f"{len(renamed_identical):,}"),
            ("top-level project codes added", ", ".join(sorted(project_codes_b-project_codes_a)) or "—"),
            ("top-level project codes removed", ", ".join(sorted(project_codes_a-project_codes_b)) or "—"),
        ]
        lines += _table(rows) + [""]

        if old_grammar != new_grammar:
            lines += [
                "The observed top-level path grammar changes between these releases; path movement is therefore",
                "partly a release-layout change and must not automatically be interpreted as manuscript reclassification.",
                "",
            ]
        if retention < 0.95:
            identity_conclusions.append(
                f"Between {older} and {newer}, only {retention:.2%} of older `src_file` paths are retained exactly."
            )

        if moved_docids:
            lines += ["#### Examples: same `docID`, no exact path retained", ""]
            ex = [("docID", older, newer)]
            for d in moved_docids[:30]:
                ex.append((f"`{d}`", "<br>".join(f"`{r.rel}`" for r in doc_a[d]), "<br>".join(f"`{r.rel}`" for r in doc_b[d])))
            lines += _table(ex) + [""]

        if renamed_identical:
            lines += ["#### Examples: byte-identical XML at different paths", ""]
            ex = [(older, newer)]
            for old_paths, new_paths in renamed_identical[:30]:
                ex.append(("<br>".join(f"`{p}`" for p in sorted(old_paths)), "<br>".join(f"`{p}`" for p in sorted(new_paths))))
            lines += _table(ex) + [""]

    lines += ["## Identity implications", ""]
    if identity_conclusions:
        lines += [*identity_conclusions, ""]
        lines += [
            "`src_file` should therefore be treated as a **release-scoped record identifier**, not as a",
            "cross-release persistent identifier. It remains suitable for unambiguous addressing inside one",
            "version of the TF corpus, provided the TF/browser tests accept raw path values.",
            "",
        ]
    else:
        lines += [
            "The measured releases do not show enough path churn by themselves to reject cross-release path stability.",
            "This is an observation, not a guarantee for future releases.",
            "",
        ]

    lines += [
        "## Interpretation rules", "",
        "- `src_file` is unique only within a specific release unless stronger stability is demonstrated separately.",
        "- A matching `docID` is evidence of manuscript/publication identity, not proof that two records are editorially equivalent.",
        "- A matching byte hash is evidence that XML payloads are identical; hashes are not proposed as persistent identifiers.",
        "- Intermediate directories remain opaque provenance until their semantics are documented independently.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    releases: dict[str, list[Record]] = {}
    for arg in argv:
        if "=" not in arg:
            raise SystemExit(f"expected LABEL=PATH, got {arg!r}")
        label, raw = arg.split("=", 1)
        releases[label] = scan(label, Path(raw).expanduser().resolve())
    print(report(releases))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
