#!/usr/bin/env python
"""Inventory TLHdig source-path structure for one or more corpus releases.

Usage:
    python programs/analyze_source_paths.py LABEL=PATH [LABEL=PATH ...]

Each PATH may point at a corpus root containing the ``CTH *_XML_*`` directories
or at an extracted archive with arbitrary wrapper directories above that root.
The script writes Markdown to stdout. It deliberately treats paths as source
metadata: it reports shapes and changes but does not assign semantics to nested
subdirectories beyond the top-level ``CTH <n>_XML_<project>`` convention.
"""
from __future__ import annotations

import hashlib
import os
import re
import sys
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path, PurePosixPath

TOP_RE = re.compile(r"^CTH ([^_]+)_XML_(.+)$")


@dataclass(frozen=True)
class Record:
    release: str
    rel: str
    cth: str
    project: str
    subdir: str
    stem: str
    docid: str
    sha256: str


def _find_root(path: Path) -> Path:
    """Find the unique directory whose immediate children are CTH corpus dirs."""
    candidates: list[Path] = []
    for current, dirs, _files in os.walk(path):
        if any(TOP_RE.match(name) for name in dirs):
            candidates.append(Path(current))
            # Once the corpus root is found, descending through ~24k XML records is
            # unnecessary and can also create false candidates from nested shards.
            dirs[:] = []
    if len(candidates) != 1:
        shown = ", ".join(str(p) for p in candidates[:5]) or "none"
        raise ValueError(
            f"cannot identify a unique corpus root below {path}: "
            f"{len(candidates)} candidates ({shown})"
        )
    return candidates[0]


def _docid(path: Path) -> str:
    try:
        root = ET.parse(path).getroot()
        value = root.findtext("AOHeader/docID")
        return (value or "").strip()
    except (ET.ParseError, OSError):
        return ""


def scan(label: str, base: Path) -> list[Record]:
    root = _find_root(base)
    out: list[Record] = []
    for path in sorted(root.rglob("*.xml")):
        rel = path.relative_to(root).as_posix()
        parts = PurePosixPath(rel).parts
        m = TOP_RE.match(parts[0]) if parts else None
        cth, project = (m.group(1), m.group(2)) if m else ("", "")
        subdir = "/".join(parts[1:-1])
        data = path.read_bytes()
        out.append(
            Record(
                release=label,
                rel=rel,
                cth=cth,
                project=project,
                subdir=subdir,
                stem=path.stem,
                docid=_docid(path),
                sha256=hashlib.sha256(data).hexdigest(),
            )
        )
    return out


def _table(rows: list[tuple[str, ...]]) -> list[str]:
    if not rows:
        return []
    return [
        "| " + " | ".join(rows[0]) + " |",
        "|" + "|".join("---" for _ in rows[0]) + "|",
        *("| " + " | ".join(r) + " |" for r in rows[1:]),
    ]


def report(releases: dict[str, list[Record]]) -> str:
    lines = ["# TLHdig source-path evolution", ""]
    lines += [
        "Generated by `programs/analyze_source_paths.py`. The report inventories path grammar and",
        "cross-release path stability. Nested directory names are reported verbatim unless their",
        "meaning is independently documented.",
        "",
        "## Per-release inventory",
        "",
    ]

    summary = [("release", "XML", "top-level projects", "path depths", "nested records", "docID != stem")]
    for label, recs in releases.items():
        projects = {r.project for r in recs if r.project}
        depths = sorted({len(PurePosixPath(r.rel).parts) for r in recs})
        nested = sum(bool(r.subdir) for r in recs)
        mismatch = sum(bool(r.docid) and r.docid != r.stem for r in recs)
        summary.append((label, f"{len(recs):,}", str(len(projects)), ", ".join(map(str, depths)), f"{nested:,}", f"{mismatch:,}"))
    lines += _table(summary) + [""]

    for label, recs in releases.items():
        lines += [f"### {label}", ""]
        bad = [r.rel for r in recs if not r.cth]
        proj = Counter(r.project for r in recs if r.project)
        lines += ["#### Top-level `_XML_<project>` suffixes", ""]
        lines += _table([("project", "documents"), *((p, f"{n:,}") for p, n in proj.most_common())]) + [""]
        lines += [f"Unmatched top-level paths: **{len(bad):,}**.", ""]

        sub = Counter(r.subdir for r in recs if r.subdir)
        lines += ["#### Intermediate directory patterns", ""]
        if sub:
            lines += _table([("intermediate path", "documents"), *((f"`{s}`", f"{n:,}") for s, n in sub.most_common(50))])
            if len(sub) > 50:
                lines += ["", f"Only the 50 most frequent of {len(sub):,} distinct intermediate paths are shown."]
        else:
            lines += ["No XML record has an intermediate directory."]
        lines += [""]

    labels = list(releases)
    if len(labels) >= 2:
        lines += ["## Adjacent-release comparisons", ""]
    for older, newer in zip(labels, labels[1:]):
        a, b = releases[older], releases[newer]
        by_rel_a = {r.rel: r for r in a}
        by_rel_b = {r.rel: r for r in b}
        common = set(by_rel_a) & set(by_rel_b)
        identical_bytes = sum(by_rel_a[p].sha256 == by_rel_b[p].sha256 for p in common)

        doc_a: dict[str, list[Record]] = defaultdict(list)
        doc_b: dict[str, list[Record]] = defaultdict(list)
        for r in a:
            if r.docid:
                doc_a[r.docid].append(r)
        for r in b:
            if r.docid:
                doc_b[r.docid].append(r)
        common_docids = set(doc_a) & set(doc_b)
        same_docid_same_path = sum(
            bool({r.rel for r in doc_a[d]} & {r.rel for r in doc_b[d]}) for d in common_docids
        )
        moved_docids = sorted(
            d for d in common_docids
            if not ({r.rel for r in doc_a[d]} & {r.rel for r in doc_b[d]})
        )

        hash_a: dict[str, list[Record]] = defaultdict(list)
        hash_b: dict[str, list[Record]] = defaultdict(list)
        for r in a:
            hash_a[r.sha256].append(r)
        for r in b:
            hash_b[r.sha256].append(r)
        renamed_identical = []
        for h in set(hash_a) & set(hash_b):
            old_paths = {r.rel for r in hash_a[h]}
            new_paths = {r.rel for r in hash_b[h]}
            if old_paths.isdisjoint(new_paths):
                renamed_identical.append((old_paths, new_paths))

        project_codes_a = {r.project for r in a if r.project}
        project_codes_b = {r.project for r in b if r.project}
        lines += [f"### {older} → {newer}", ""]
        rows = [
            ("measure", "value"),
            ("paths in older", f"{len(a):,}"),
            ("paths in newer", f"{len(b):,}"),
            ("exact paths retained", f"{len(common):,} ({len(common)/len(a):.2%} of older)" if a else "0"),
            ("retained paths with byte-identical XML", f"{identical_bytes:,}"),
            ("docIDs present in both", f"{len(common_docids):,}"),
            ("common docIDs retaining at least one path", f"{same_docid_same_path:,}"),
            ("common docIDs with no retained path", f"{len(moved_docids):,}"),
            ("byte-identical records found only at different paths", f"{len(renamed_identical):,}"),
            ("project codes added", ", ".join(sorted(project_codes_b-project_codes_a)) or "—"),
            ("project codes removed", ", ".join(sorted(project_codes_a-project_codes_b)) or "—"),
        ]
        lines += _table(rows) + [""]

        if moved_docids:
            lines += ["#### Examples: same `docID`, no path retained", ""]
            ex = [("docID", older, newer)]
            for d in moved_docids[:30]:
                ex.append((f"`{d}`", "<br>".join(f"`{r.rel}`" for r in doc_a[d]), "<br>".join(f"`{r.rel}`" for r in doc_b[d])))
            lines += _table(ex) + [""]

        if renamed_identical:
            lines += ["#### Examples: byte-identical XML at different paths", ""]
            ex = [(older, newer)]
            for old_paths, new_paths in renamed_identical[:30]:
                ex.append(("<br>".join(f"`{p}`" for p in sorted(old_paths)), "<br>".join(f"`{p}`" for p in sorted(new_paths))))
            lines += _table(ex) + [""]

    lines += [
        "## Interpretation rules", "",
        "- `src_file` can be called unique only within a specific release unless the comparison above demonstrates stronger stability.",
        "- A matching `docID` is evidence of manuscript/publication identity, not proof that two records are editorially equivalent.",
        "- A matching byte hash is evidence that XML payloads are identical; hashes are not proposed as persistent identifiers.",
        "- Intermediate directories remain opaque provenance until their semantics are documented independently.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    releases: dict[str, list[Record]] = {}
    for arg in argv:
        if "=" not in arg:
            raise SystemExit(f"expected LABEL=PATH, got {arg!r}")
        label, raw = arg.split("=", 1)
        releases[label] = scan(label, Path(raw).expanduser().resolve())
    print(report(releases))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
