#!/usr/bin/env python
"""Generate reports/census.md from the loaded TF dataset.

Hand-copying counts into the README and KNOWN-ISSUES is what left the docs claiming
`cluster` was missing while 655,336 of them sat in otype.tf. Every number here is read
from the dataset that actually shipped.

This command is one release gate. It does not write BUILD-COMPLETE; only
`programs/release_check.py` may certify that the complete required gate set passed.
"""
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import TF_VERSION
from tlhdig.paths import REPORTS, ROOT

FAMILIES = {"del": "missing", "laes": "laes", "ras": "ras", "add": "add", "quot": "quot"}


def main() -> int:
    from tf.fabric import Fabric

    out = ROOT / "tf" / TF_VERSION
    TF = Fabric(locations=str(out), silent="deep")
    api = TF.loadAll(silent="deep") or TF.api
    if api is None:
        print("census: dataset does not load")
        return 1
    F, L, T = api.F, api.L, api.T
    have = set(api.Fall())

    counts = {t: len(F.otype.s(t)) for t in F.otype.all}
    lines = [
        "# Census of `tf/" + TF_VERSION + "`",
        "",
        "Generated by `programs/census.py` from the loaded dataset. Do not hand-edit.",
        "",
        "## Features",
        "",
        f"{len(api.Fall()) - 1} node features, {len(api.Eall()) - 1} edge features "
        f"(excluding the `otype`/`oslots` warps), slot type `{F.otype.slotType}`.",
        "",
        "## Nodes",
        "",
        "| type | count |",
        "|---|---|",
    ]
    for t, n in sorted(counts.items(), key=lambda x: -x[1]):
        lines.append(f"| `{t}` | {n:,} |")
    lines += ["", f"**total** {sum(counts.values()):,} · slot type `{F.otype.slotType}`", ""]

    ext = Counter()
    spanned = {f: set() for f in FAMILIES.values()}
    for c in F.otype.s("cluster"):
        t = F.type.v(c)
        w = F.width.v(c) or 0
        ext[(t, "point" if w == 0 else "span")] += 1
        if w:
            spanned[FAMILIES.get(t, t)].update(L.d(c, otype="sign"))
    lines += ["## Damage ranges", "", "| family | spans | points |", "|---|---|---|"]
    for fam in sorted({k for k, _ in ext}):
        lines.append(f"| `{fam}` | {ext[(fam,'span')]:,} | {ext[(fam,'point')]:,} |")
    lines.append("")

    problems = []
    lines += ["## Invariants", "", "| check | result |", "|---|---|"]

    for fam, feat in FAMILIES.items():
        if feat not in have:
            continue
        f = getattr(F, feat)
        flagged = {s for s in F.otype.s("sign") if f.v(s)}
        ok = flagged == spanned[feat]
        problems += [] if ok else [f"{feat}: flags != positive-width cluster coverage"]
        lines.append(
            f"| `{feat}` flags == cluster coverage | "
            f"{'OK' if ok else 'FAIL'} ({len(flagged):,} vs {len(spanned[feat]):,}) |"
        )

    docs = counts.get("document", 0)
    src = len(list((ROOT / "corpus").rglob("*.xml")))
    excl = len(
        [
            line
            for line in (ROOT / "programs" / "excluded.txt").read_text(encoding="utf8").splitlines()
            if line.strip() and not line.startswith("#")
        ]
    )
    ok = src == docs + excl
    problems += [] if ok else [f"documents: {src} != {docs} + {excl}"]
    lines.append(f"| sources == documents + exclusions | {'OK' if ok else 'FAIL'} ({src:,} = {docs:,} + {excl}) |")

    probe = T.nodeFromSection(("KUB 21.8", "Vs. II", "1′"))
    problems += [] if probe else ["section addressing probe failed"]
    lines.append(f"| section addressing | {'OK' if probe else 'FAIL'} |")

    dup = Counter(F.docid.v(d) for d in F.otype.s("document"))
    ndup = sum(1 for v in dup.values() if v > 1)
    lines.append(f"| docid unique (known open) | {ndup:,} values on >1 document |")
    lines.append("")

    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "census.md").write_text("\n".join(lines) + "\n", encoding="utf8")
    print("\n".join(lines[4:]))
    if problems:
        print("\nCENSUS FAILED:")
        for problem in problems:
            print("  " + problem)
        return 1
    print("\nall census invariants hold -- release_check.py owns BUILD-COMPLETE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
