#!/usr/bin/env python
"""Independent gate: count damage markers in the SOURCE, compare against the TF graph.

The census asserts `flags == cluster coverage`, but flags are *derived* from cluster
coverage, so that check cannot fail however wrong the extents are:

    wrong extent -> wrong flags derived from it -> census compares wrong with wrong -> OK

This gate is independent. It re-reads the repaired source bytes, counts every
`<del_in/>`-family marker per family, and requires that number to equal the count of
cluster endpoints in the published dataset that claim to come from a real marker.
Extents are a modelling choice; marker conservation is not.
"""
import sys
from collections import Counter
from pathlib import Path

import lxml.etree as LE

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import TF_VERSION, brackets as B, repair
from tlhdig.paths import CORPUS, ENCRYPTED, PATCHES, REPORTS, ROOT, corpus_files, rel


def count_source() -> Counter:
    man = repair.read_manifest(PATCHES) if PATCHES.exists() else {}
    c = Counter()
    for f in corpus_files():
        r = rel(f)
        if r == ENCRYPTED:
            continue
        data = f.read_bytes()
        if r in man:
            try:
                data = repair.apply(data, man[r][1], expect_sha=man[r][0])
            except repair.PatchError:
                continue
        try:
            root = LE.fromstring(data)
        except Exception:
            continue
        text = root.find("body/div1/text")
        if text is None:
            continue
        for node in text.iter():
            t = node.tag
            if not isinstance(t, str):
                continue
            if t in B.OPEN:
                c[(B.OPEN[t], "open")] += 1
            elif t in B.CLOSE:
                c[(B.CLOSE[t], "close")] += 1
    return c


def count_tf() -> Counter:
    from tf.fabric import Fabric

    TF = Fabric(locations=str(ROOT / "tf" / TF_VERSION), silent="deep")
    api = TF.loadAll(silent="deep") or TF.api
    if api is None:
        raise SystemExit("check_markers: dataset does not load")
    F = api.F
    c = Counter()
    for n in F.otype.s("cluster"):
        fam = F.type.v(n)
        if F.from_open_marker.v(n):
            c[(fam, "open")] += 1
        if F.from_close_marker.v(n):
            c[(fam, "close")] += 1
    return c


def main() -> int:
    src = count_source()
    tf = count_tf()
    fams = sorted({f for f, _ in src} | {f for f, _ in tf})
    lines = ["| family | kind | source | TF | |", "|---|---|---|---|---|"]
    bad = []
    for fam in fams:
        for kind in ("open", "close"):
            a, b = src[(fam, kind)], tf[(fam, kind)]
            ok = a == b
            if not ok:
                bad.append(f"{fam}/{kind}: source {a:,} != TF {b:,}")
            lines.append(f"| `{fam}` | {kind} | {a:,} | {b:,} | {'OK' if ok else 'LOST'} |")
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "markers.md").write_text(
        "# Source marker conservation\n\nGenerated by `programs/check_markers.py`.\n\n"
        + "\n".join(lines)
        + "\n",
        encoding="utf8",
    )
    print("\n".join(lines))
    if bad:
        print("\nMARKER CONSERVATION FAILED:")
        for b in bad:
            print("  " + b)
        return 1
    print("\nevery source marker is accounted for in the graph")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
