#!/usr/bin/env python
"""Independent gate: every structural element in the source must be a node in the graph.

The census compares the graph against itself -- induced flags against the cluster
coverage they are derived from -- so it cannot fail however much the graph is missing.
This counts `<lb>`, `<clb>` and `<note>` in the repaired source stream and requires the
shipped `line`, `colon` and `note` node counts to match.

It reads otype.tf rather than loading Text-Fabric, so it runs in the time it takes to
re-parse the corpus rather than the 12 minutes a full load costs.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import TF_VERSION, repair, structure
from tlhdig.paths import ENCRYPTED, PATCHES, REPORTS, ROOT, corpus_files, rel


def main() -> int:
    tf_dir = ROOT / "tf" / TF_VERSION
    if not (tf_dir / "otype.tf").is_file():
        print(f"no dataset at {tf_dir}; build it first")
        return 1

    patches = repair.read_manifest(PATCHES) if PATCHES.exists() else {}
    src, docs = structure.count_corpus(corpus_files(), patches, ENCRYPTED, rel)
    graph = structure.graph_counts(tf_dir)

    lines = [
        "# Source structure conservation",
        "",
        "Generated by `programs/check_structure.py`. Counts elements in the repaired",
        f"source stream over the {docs:,} documents that convert, and compares them with",
        "the node counts in the shipped `otype.tf`.",
        "",
        "| element | node type | source | graph | |",
        "|---|---|---:|---:|---|",
    ]
    problems = []
    for tag, ntype in sorted(structure.ELEMENT_TO_TYPE.items()):
        s, g = src[ntype], graph.get(ntype, 0)
        ok = s == g
        if not ok:
            problems.append(f"{ntype}: source {s:,} != graph {g:,} (deficit {s - g:,})")
        lines.append(
            f"| `<{tag}>` | `{ntype}` | {s:,} | {g:,} | {'OK' if ok else f'LOST {s - g:,}'} |"
        )

    # Words are not a 1:1 element->type mapping: a contentless <w> becomes a `layout`
    # node instead, so the source's top-level words must equal word + layout.
    src_w = src["word"]
    got_w = graph.get("word", 0) + graph.get("layout", 0)
    deficit = src_w - got_w
    if deficit > structure.KNOWN_WORD_DEFICIT:
        problems.append(
            f"word: source {src_w:,} != word+layout {got_w:,} (deficit {deficit:,}, "
            f"known {structure.KNOWN_WORD_DEFICIT:,}) -- this got worse"
        )
    status = "OK" if deficit == 0 else f"known open: {deficit:,}"
    lines.append(f"| `<w>` (top level) | `word`+`layout` | {src_w:,} | {got_w:,} | {status} |")
    lines.append("")
    lines.append(
        f"The {deficit:,} missing words are a known open defect: a nested `<w>` is skipped "
        "as covered by the enclosing word's bytes, and when that enclosing word yields no "
        "slots its children are lost with it. The gate fails only if the number grows."
    )
    lines.append("")

    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "structure.md").write_text("\n".join(lines) + "\n", encoding="utf8")
    print("\n".join(lines))
    if problems:
        print("STRUCTURE GATE FAILED:")
        for p in problems:
            print("  " + p)
        return 1
    print("every source structure survives into the graph")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
