#!/usr/bin/env python
"""Contract B gate: every source element must have a declared destination.

A tag nobody thought about does not fail anything today -- it simply survives in
`srcxml` with its meaning invisible. This makes that a decision: to add an element to
the corpus, someone must say where it goes, even if the answer is "raw".
"""
import sys
from collections import Counter
from pathlib import Path

import lxml.etree as LE

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import repair, tags
from tlhdig.paths import ENCRYPTED, PATCHES, REPORTS, corpus_files, rel


def main() -> int:
    man = repair.read_manifest(PATCHES) if PATCHES.exists() else {}
    found = Counter()
    for f in corpus_files():
        r = rel(f)
        if r == ENCRYPTED:
            continue
        data = f.read_bytes()
        entry = man.get(r)
        if entry:
            try:
                data = repair.apply(data, entry[1], expect_sha=entry[0])
            except repair.PatchError:
                continue
        try:
            root = LE.fromstring(data)
        except Exception:
            continue
        text = root.find(".//{*}text")
        if text is None:
            continue
        for el in text.iter():
            if isinstance(el.tag, str):
                name = el.tag.split("}")[-1] if "}" in el.tag else el.tag
                found[name] += 1

    missing = tags.undeclared(found)
    by_kind: dict[str, list[tuple[str, int]]] = {}
    for name, n in found.most_common():
        by_kind.setdefault(tags.DESTINATION.get(name, "UNDECLARED"), []).append((name, n))

    lines = ["# AOxml element inventory", "",
             "Generated by `programs/check_tags.py` from the repaired source stream.",
             f"{len(found)} distinct element names under `<text>`.", ""]
    for kind, meaning in list(tags.KINDS.items()) + [("UNDECLARED", "no destination declared")]:
        items = by_kind.get(kind)
        if not items:
            continue
        lines.append(f"## `{kind}` — {meaning}")
        lines.append("")
        lines.append("| element | occurrences |")
        lines.append("|---|---:|")
        lines.extend(f"| `{n}` | {c:,} |" for n, c in items)
        lines.append("")

    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "tags.md").write_text("\n".join(lines) + "\n", encoding="utf8")
    for kind in tags.KINDS:
        items = by_kind.get(kind, [])
        print(f"  {kind:<12} {len(items):>3} elements, {sum(c for _, c in items):>9,} occurrences")
    if missing:
        print(f"\nTAG GATE FAILED: {len(missing)} element(s) with no declared destination")
        for m in missing:
            print(f"  {m}  ({found[m]:,} occurrences)")
        return 1
    print(f"\nall {len(found)} element names have a declared destination -> reports/tags.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
