#!/usr/bin/env python
"""Gate: is `srcxml` the sole record of anything?

The provenance module can only be separated from the linguistic layer if nothing
inside `srcxml` exists only there. Everything it holds should be modelled: wrappers as
`sgr`/`agr`/`det`/`num`, damage as `cluster` nodes with offsets, `corr`, `subscr`,
`materlect`, `surpl` and `note` as their own features, and anything else named on the
sign by `othertags`.

Two earlier passes each found survivors -- 212 signs whose only record of a long-form
`AO:Sumgram` was the raw string, then 149 more holding `ras_X`, `AkkGLOS`,
`PARSER_ERROR` and leaked ODF styling. This is what stops a third going unnoticed.
"""
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import PROVENANCE_DIR, TF_VERSION, appcheck, compact, tags
from tlhdig.paths import REPORTS, ROOT

TAG = re.compile(r"<(/?)([A-Za-z_][-\w.:]*)")


def main() -> int:
    tf_dir = ROOT / "tf" / TF_VERSION
    prov = ROOT / PROVENANCE_DIR / TF_VERSION
    src = prov / "srcxml.tf"
    if not src.is_file():
        src = tf_dir / "srcxml.tf"
    if not src.is_file():
        print("no srcxml to check; build first")
        return 1

    ranges = appcheck.node_ranges(tf_dir)
    lo, hi = ranges["sign"]
    othertags = {}
    ot = tf_dir / "othertags.tf"
    if ot.is_file():
        _, body = compact._split(ot)
        for nodes, v in compact._parse(body):
            for n in nodes:
                othertags[n] = v

    modelled = {k for k, v in tags.DESTINATION.items() if v not in ("raw", "malformed")}
    unrecorded = Counter()
    signs_bad = 0
    _, body = compact._split(src)
    for nodes, value in compact._parse(body):
        if "<" not in value:
            continue
        names = {m.group(2) for m in TAG.finditer(value)}
        for n in nodes:
            named = set((othertags.get(n) or "").split())
            missing = {
                t for t in names
                if t.split(":")[-1] not in modelled and t not in named
            }
            if missing:
                signs_bad += 1
                for t in missing:
                    unrecorded[t] += 1

    lines = [
        "# Is `srcxml` the sole record of anything?",
        "",
        "Generated by `programs/check_provenance_split.py`. Every element inside a sign's",
        "`srcxml` must be modelled as a feature, or named on that sign by `othertags`.",
        "Only then can the provenance module be separated without losing information.",
        "",
        f"- sign slots: {hi - lo + 1:,}",
        f"- signs carrying an unrecorded element: **{signs_bad:,}**",
        "",
    ]
    if unrecorded:
        lines += ["| element | signs |", "|---|---:|"]
        lines += [f"| `{t}` | {c:,} |" for t, c in unrecorded.most_common()]
        lines.append("")
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "provenance_split.md").write_text("\n".join(lines) + "\n", encoding="utf8")
    print("\n".join(lines))
    if signs_bad:
        print(f"SPLIT GATE FAILED: {signs_bad:,} signs would lose information")
        return 1
    print("srcxml is the sole record of nothing; the provenance split is lossless")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
