#!/usr/bin/env python
"""Contract B: every source construct has an explicit declared disposition.

Body markup and AOHeader metadata are inventoried separately because their preservation
semantics differ. Body ``raw`` survives in provenance; header ``known-unpreserved``
means exactly the opposite and remains visible until #57/#58 resolve it.
"""
from __future__ import annotations

import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

import lxml.etree as LE

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import repair, tags
from tlhdig.paths import ENCRYPTED, PATCHES, REPORTS, corpus_files, rel


def _local(name: str) -> str:
    return LE.QName(name).localname if name.startswith("{") else name


@dataclass
class Inventory:
    body_elements: Counter = field(default_factory=Counter)
    header_elements: Counter = field(default_factory=Counter)
    header_attrs: Counter = field(default_factory=Counter)

    def add(self, other: "Inventory") -> None:
        self.body_elements.update(other.body_elements)
        self.header_elements.update(other.header_elements)
        self.header_attrs.update(other.header_attrs)


def inventory_root(root) -> Inventory:
    """Inventory one parsed AOxml root, keeping body/header namespaces distinct."""
    inv = Inventory()
    text = root.find(".//{*}text")
    if text is not None:
        for el in text.iter():
            if isinstance(el.tag, str):
                inv.body_elements[_local(el.tag)] += 1

    header = next(
        (el for el in root.iter() if isinstance(el.tag, str) and _local(el.tag) == "AOHeader"),
        None,
    )
    if header is not None:
        for el in header.iter():
            if not isinstance(el.tag, str):
                continue
            name = _local(el.tag)
            inv.header_elements[name] += 1
            for attr in el.attrib:
                inv.header_attrs[(name, _local(attr))] += 1
    return inv


def _element_sections(found: Counter, destinations: dict, kinds: dict) -> list[str]:
    by_kind: dict[str, list[tuple[str, int]]] = {}
    for name, n in found.most_common():
        by_kind.setdefault(destinations.get(name, "UNDECLARED"), []).append((name, n))
    lines = []
    for kind, meaning in list(kinds.items()) + [("UNDECLARED", "no disposition declared")]:
        items = by_kind.get(kind)
        if not items:
            continue
        lines += [f"### `{kind}` — {meaning}", "", "| element | occurrences |", "|---|---:|"]
        lines.extend(f"| `{name}` | {count:,} |" for name, count in items)
        lines.append("")
    return lines


def render_report(inv: Inventory) -> str:
    """Render a regioned Contract-B report; known header loss is never called raw."""
    lines = [
        "# AOxml Contract B inventory", "",
        "Generated by `programs/check_tags.py` from the repaired source stream.", "",
        "## Body `<text>` element inventory", "",
        f"{len(inv.body_elements)} distinct element names under `<text>`.", "",
    ]
    lines.extend(_element_sections(inv.body_elements, tags.DESTINATION, tags.KINDS))
    lines += [
        "## `AOHeader` element inventory", "",
        f"{len(inv.header_elements)} distinct element names under `AOHeader`.", "",
        "`known-unpreserved` is an explicit current loss disposition; it does not mean preserved.", "",
    ]
    lines.extend(_element_sections(inv.header_elements, tags.HEADER_DESTINATION, tags.HEADER_KINDS))

    by_kind: dict[str, list[tuple[tuple[str, str], int]]] = {}
    for pair, n in inv.header_attrs.most_common():
        by_kind.setdefault(tags.HEADER_ATTR_DESTINATION.get(pair, "UNDECLARED"), []).append((pair, n))
    lines += [
        "## `AOHeader` attribute inventory", "",
        f"{len(inv.header_attrs)} distinct element/attribute pairs under `AOHeader`.", "",
    ]
    for kind, meaning in list(tags.HEADER_KINDS.items()) + [("UNDECLARED", "no disposition declared")]:
        items = by_kind.get(kind)
        if not items:
            continue
        lines += [f"### `{kind}` — {meaning}", "", "| element@attribute | occurrences |", "|---|---:|"]
        lines.extend(f"| `{el}@{attr}` | {count:,} |" for (el, attr), count in items)
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    man = repair.read_manifest(PATCHES) if PATCHES.exists() else {}
    inv = Inventory()
    for f in corpus_files():
        r = rel(f)
        if r == ENCRYPTED:
            continue
        data = f.read_bytes()
        entry = man.get(r)
        if entry:
            try:
                data = repair.apply(data, entry[1], expect_sha=entry[0])
            except repair.PatchError:
                continue
        try:
            root = LE.fromstring(data)
        except Exception:
            continue
        inv.add(inventory_root(root))

    missing_body = tags.undeclared(inv.body_elements)
    missing_header = tags.header_undeclared(inv.header_elements)
    missing_attrs = tags.header_attrs_undeclared(inv.header_attrs)

    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "tags.md").write_text(render_report(inv), encoding="utf8")

    if missing_body or missing_header or missing_attrs:
        print("CONTRACT B FAILED")
        if missing_body:
            print(f"  undeclared body elements ({len(missing_body)}):")
            for name in missing_body:
                print(f"    {name} ({inv.body_elements[name]:,})")
        if missing_header:
            print(f"  undeclared AOHeader elements ({len(missing_header)}):")
            for name in missing_header:
                print(f"    {name} ({inv.header_elements[name]:,})")
        if missing_attrs:
            print(f"  undeclared AOHeader element@attribute pairs ({len(missing_attrs)}):")
            for el, attr in missing_attrs:
                print(f"    {el}@{attr} ({inv.header_attrs[(el, attr)]:,})")
        return 1

    known_loss_elements = sum(
        inv.header_elements[name]
        for name, kind in tags.HEADER_DESTINATION.items()
        if kind in {"known-unpreserved", "malformed-unpreserved"}
    )
    known_loss_attrs = sum(
        inv.header_attrs[pair]
        for pair, kind in tags.HEADER_ATTR_DESTINATION.items()
        if kind in {"known-unpreserved", "malformed-unpreserved"}
    )
    print(
        f"Contract B covers {len(inv.body_elements)} body elements, "
        f"{len(inv.header_elements)} header elements and {len(inv.header_attrs)} header attribute pairs"
    )
    print(
        f"explicit current header loss: {known_loss_elements:,} element occurrences, "
        f"{known_loss_attrs:,} attribute occurrences -> reports/tags.md"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
