#!/usr/bin/env python
"""Gate: how much of the cuneiform is laid out per sign, and by which mechanism.

Reads the `.tf` files directly, so it runs in seconds and can sit in CI beside
check_structure.py rather than waiting on a Text-Fabric load.

The floors are pinned. Coverage may rise freely; a drop fails, because every mechanism
here was justified by measurement and losing one silently would undo that. The by-level
breakdown is reported because the levels are not equally strong evidence -- a consumer
filtering `cu_aligned=1` cares if level 1 shrinks even when the total holds.
"""
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import TF_VERSION, appcheck, compact
from tlhdig.paths import REPORTS, ROOT

# Measured on the build that introduced phases 0-3. Raise these when coverage improves;
# never lower one to make a build pass.
FLOOR_SIGNS = 3_017_385
FLOOR_EXACT = 191_809          # cu_aligned == 1, the strongest evidence

LABEL = {
    0: "not aligned",
    1: "counts matched, zipped",
    2: "damage placeholders absorbed",
    3: "compound logogram expanded",
    4: "numeral derived",
}


def main() -> int:
    d = ROOT / "tf" / TF_VERSION
    if not (d / "cu_aligned.tf").is_file():
        print("no alignment in this dataset; build first")
        return 1
    r = appcheck.node_ranges(d)
    llo, lhi = r["line"]
    slo, shi = r["sign"]

    levels = Counter()
    _, body = compact._split(d / "cu_aligned.tf")
    for nodes, v in compact._parse(body):
        levels[int(v or 0)] += sum(1 for n in nodes if llo <= n <= lhi)

    signs = 0
    _, body = compact._split(d / "cu_sign.tf")
    for nodes, _v in compact._parse(body):
        signs += sum(1 for n in nodes if slo <= n <= shi)

    total_lines = sum(levels.values())
    total_signs = shi - slo + 1
    lines = [
        "# Cuneiform alignment coverage",
        "",
        "Generated by `programs/check_alignment.py`. How much of the line-level `cu`",
        "is laid out per sign, and by which mechanism. Higher levels are weaker",
        "evidence: a consumer wanting only the safest material filters `cu_aligned=1`.",
        "",
        "| level | meaning | lines | |",
        "|---:|---|---:|---:|",
    ]
    for lv in sorted(levels):
        n = levels[lv]
        lines.append(f"| {lv} | {LABEL.get(lv, '?')} | {n:,} | {n/total_lines*100:.1f}% |")
    lines += [
        "",
        f"- signs carrying `cu_sign`: **{signs:,}** of {total_signs:,} "
        f"({signs/total_signs*100:.1f}%)",
        "",
    ]
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "alignment.md").write_text("\n".join(lines) + "\n", encoding="utf8")
    print("\n".join(lines))

    problems = []
    if signs < FLOOR_SIGNS:
        problems.append(f"signs with cu_sign fell: {signs:,} < {FLOOR_SIGNS:,}")
    if levels[1] < FLOOR_EXACT:
        problems.append(f"exact alignments fell: {levels[1]:,} < {FLOOR_EXACT:,}")
    if problems:
        print("ALIGNMENT GATE FAILED:")
        for p in problems:
            print("  " + p)
        return 1
    print("alignment coverage holds")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
