#!/usr/bin/env python
"""A stratified sample of the sign alignment, for a Hittitologist to read.

`check_alignment.py` measures agreement with a table learned from the corpus itself.
That is an independent witness for levels 2-4 and a useful one, but it can only catch
the errors the table has an opinion about: a reading it never saw often enough, or a
disagreement between two equally learned spellings, passes silently either way.

The only check that closes that gap is a person reading lines. This draws a fixed,
reproducible sample from each mechanism -- the same lines every time the corpus does not
change, so a reviewer's notes stay valid across builds -- and lays each one out as the
cuneiform, the transliteration, and what was matched to what.

    .venv/bin/python programs/sample_alignment.py [per-level]

Writes `reports/alignment-sample.md`.
"""
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tlhdig import TF_VERSION, appcheck, compact, cuneiform
from tlhdig.paths import REPORTS, ROOT

PER_LEVEL = 25
SEED = 20260831        # fixed, so the sample is the same on every build

LABEL = {
    1: "counts matched, zipped one to one",
    2: "damage placeholders absorbed",
    3: "compound logogram expanded",
    4: "numeral derived",
}


def _feat(d, name, lo, hi):
    out = {}
    p = d / f"{name}.tf"
    if not p.is_file():
        return out
    _, body = compact._split(p)
    for nodes, v in compact._parse(body):
        for n in nodes:
            if lo <= n <= hi:
                out[n] = v
    return out


def main(per_level: int = PER_LEVEL) -> int:
    d = ROOT / "tf" / TF_VERSION
    if not (d / "cu_aligned.tf").is_file():
        print("no alignment in this dataset; build first")
        return 1
    r = appcheck.node_ranges(d)
    llo, lhi = r["line"]
    slo, shi = r["sign"]
    dlo, dhi = r["document"]

    cu = _feat(d, "cu", llo, lhi)
    aligned = _feat(d, "cu_aligned", llo, lhi)
    method = _feat(d, "cu_method", llo, lhi)
    lnno = _feat(d, "lnno", llo, lhi)
    sym = _feat(d, "sym", slo, shi)
    cu_sign = _feat(d, "cu_sign", slo, shi)
    anchor = _feat(d, "anchor", slo, shi)
    docid = _feat(d, "docid", dlo, dhi)

    line_slots, doc_slots = {}, {}
    implicit = 1
    for raw in compact._split(d / "oslots.tf")[1]:
        if "\t" in raw:
            spec, _, val = raw.partition("\t")
            nodes = compact._nodes_of(spec)
            if not nodes:
                continue
        else:
            nodes, val = [implicit], raw
        implicit = max(nodes) + 1
        for n in nodes:
            if llo <= n <= lhi:
                line_slots[n] = [s for s in compact._nodes_of(val) if not anchor.get(s)]
            elif dlo <= n <= dhi:
                doc_slots[n] = compact._nodes_of(val)
    where = {}
    for dn, ss in doc_slots.items():
        if ss:
            where[dn] = (ss[0], ss[-1])

    def doc_of(slot):
        for dn, (a, b) in where.items():
            if a <= slot <= b:
                return docid.get(dn, "?")
        return "?"

    by_level = {lv: [] for lv in LABEL}
    for ln, v in aligned.items():
        lv = int(v or 0)
        if lv in by_level and line_slots.get(ln):
            by_level[lv].append(ln)

    rnd = random.Random(SEED)
    out = [
        "# Alignment sample for review",
        "",
        f"Generated by `programs/sample_alignment.py`, seed {SEED}: the same lines on "
        "every build, so notes on them keep their meaning.",
        "",
        "Each row is one sign. `cu_sign` empty means the alignment declined to assign "
        "anything there, which is a refusal, not a claim that the sign is absent.",
        "",
        "What to look for, per mechanism: at level 1 that the reading and the sign are "
        "the same sign; at level 2 that the placeholders removed were the ones standing "
        "for nothing in the transliteration; at level 3 that the multi-sign spelling "
        "really is that reading's; at level 4 that the number is written the way the "
        "sign values say it is.",
        "",
    ]
    for lv in sorted(by_level):
        pool = sorted(by_level[lv])
        if not pool:
            continue
        take = rnd.sample(pool, min(per_level, len(pool)))
        out += [
            f"## Level {lv} — {LABEL[lv]}",
            "",
            f"{len(pool):,} lines; {len(take)} sampled.",
            "",
        ]
        for ln in sorted(take):
            slots = line_slots[ln]
            ref = f"{doc_of(slots[0])} {lnno.get(ln) or ''}".strip()
            out += [
                f"**{ref}** — `cu_method={method.get(ln) or ''}`",
                "",
                f"- cuneiform: {cu.get(ln) or ''}",
                f"- reading: {' '.join((sym.get(s) or '·') for s in slots)}",
                "",
                "| reading | assigned |",
                "|---|---|",
            ]
            for s in slots:
                out.append(f"| {sym.get(s) or '·'} | {cu_sign.get(s) or ''} |")
            out.append("")
    REPORTS.mkdir(exist_ok=True)
    path = REPORTS / "alignment-sample.md"
    path.write_text("\n".join(out) + "\n", encoding="utf8")
    print(f"wrote {path} — {sum(min(per_level, len(v)) for v in by_level.values())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(int(sys.argv[1]) if len(sys.argv) > 1 else PER_LEVEL))
